### ISSUE TITLE
Some formats don't parse

### ISSUE THREAD

**Issue by sckott** [cschwarz/wkx#8]
As far as I can tell, this format is acceptable WKT:

`MULTIPOINT((10 40), (40 30), (20 20), (30 10))`

However, this doesn't work

```javascript
> var geometry = wkx.Geometry.parse("MULTIPOINT((10 40), (40 30), (20 20), (30 10))");
Error: Expected coordinate pair
    at WktParser.matchCoordinate (/Users/sacmac/node_modules/wkx/lib/wktparser.js:76:15)
    at WktParser.matchCoordinates (/Users/sacmac/node_modules/wkx/lib/wktparser.js:85:31)
    at Function.MultiPoint._parseWkt (/Users/sacmac/node_modules/wkx/lib/multipoint.js:27:59)
    at Function.Geometry._parseWkt (/Users/sacmac/node_modules/wkx/lib/geometry.js:58:27)
    at Function.Geometry.parse (/Users/sacmac/node_modules/wkx/lib/geometry.js:24:25)
    at repl:1:29
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
```

But this does, without the parentheses surrounding each point pair

```javascript
> var geometry = wkx.Geometry.parse("MULTIPOINT(10 40, 40 30, 20 20, 30 10)");
undefined
```

Any chance you could allow parsing of formats like `MULTIPOINT((10 40), (40 30), (20 20), (30 10))` ?

**Comment by cschwarz** [comment]
Should be fixed now.

Thanks for reporting.

**Comment by sckott** [comment]
trying

**Comment by sckott** [comment]
cool, works
